export default {
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    UPDATE_HOUSES: 'UPDATE_HOUSES',
    SET_HOUSE_TOTAL: 'SET_HOUSE_TOTAL',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    SET_UNIQUE_YEARS: 'SET_UNIQUE_YEARS',
    SET_FILTER_STRING: 'SET_FILTER_STRING',
    SET_FILTER_CONFIGURATION: 'SET_FILTER_CONFIGURATION'
}